spring.application.name=userservice

server.port=8081

spring.data.mongodb.uri=mongodb+srv://ruchita7119:Ruchita7119@cluster0.xfmgh.mongodb.net/ordernow?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

jwt.secret=OrderNowSuperSecretKeyForJwtTokenGeneration2026OrderNow
jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always